tasks:
- install:
- ceph:
- rbd:
    all:
      image_format: 2      
      image_features: ['layering', 'object map', 'fast-diff']       
- workunit:
    clients:
      all: [fs/misc/trivial_sync.sh]
